(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(*
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*)

(*
NB: The package have been tested extensively, on Mathemativa v 7.0, 
but there is no guarantee that the package yields correct results.

If you find the Lambda package useful for doing research, acknowledging 
the author\[CloseCurlyQuote]s work by proper reference to the package would be appreciated.

Any comments, bugs and especially improvements are welcome.

Version 1.1
*)

BeginPackage["Lambda`"];

Print["Lambda: A Mathematica-package for operator product expansions in vertex algebras."];
Print["Copyright 2010 Joel Ekstrand"];


Clear["Lambda`*"];
Clear["Lambda`Private`*"];


dim::"usage"="dim is the trace of the special field delta.";
TD::"usage"="TD[expr] is the even derivative on expr. Denoted \[Square]expr, defining the command Square[expr].";
SD::"usage"="SD[expr] is the odd derivative on expr. Denoted \[Del]expr, defining the command Del[expr].";
Field::"usage"="Field[sym_Symbol,downindices_List,upindices_List,derivatives_List] is a field with symbol sym, \
lower indices are given by downindices, upper indices by upindices and the derivatives by derivatives. A symbol \
with a hat,^, is interpreted as a field, and the indices are in placed as \
 \!\(\*SubsuperscriptBox[OverscriptBox[\"sym\", \"^\"], 
RowBox[{
RowBox[{\"l1\", \" \", \"l2\"}], \",\", \" \", 
RowBox[{\"d1\", \" \", \"d2\"}]}], 
RowBox[{\"u1\", \" \", \"u2\"}]]\), with a comma separating the lower indices from the derivative indices.";
NormalOrder::"usage"="NormalOrder[a,b] represents the normal ordered product of the fields a and b. \
It is denoted (a\[SmallCircle]b), i.e. using the character SmallCircle. Write the input as \!\(\*
StyleBox[\"Esc\", \"KeyEvent\"]\)\!\(\*
StyleBox[\"\[ThinSpace]\", \"InlineCode\"]\)\!\(\*
StyleBox[\"sc\", \"InlineCode\"]\)\!\(\*
StyleBox[\"\[ThinSpace]\", \"InlineCode\"]\)\!\(\*
StyleBox[\"Esc\", \"KeyEvent\"]\)\!\(\*
StyleBox[\" \", \"KeyEvent\"]\)\!\(\*
StyleBox[\"b\", \"KeyEvent\"]\)\!\(\*
StyleBox[\".\", \"KeyEvent\"]\)\!\(\*
StyleBox[\" \", \"KeyEvent\"]\)\!\(\*
StyleBox[
RowBox[{\"\\\\\\\\\", \"n\"}], \"KeyEvent\"]\)If more terms are given, the normal ordering binds from the right, i.e. a\[SmallCircle]b\[SmallCircle]c are interpreted as (a\[SmallCircle]b)\[SmallCircle]c.";
LambdaBracket::"usage"="LambdaBracket[a,b] calculates the \[Lambda]-bracket between a and b.";
LambdaBracketChangeOrder::"usage"="LambdaBracketChangeOrder[a,b] calculates [\!\(\*SubscriptBox[\"a\", \"\[Lambda]\"]\)b], from the bracket [\!\(\*SubscriptBox[\"b\", \"\[Lambda]\"]\)a], using skew-symmetry.";
Grading::"usage"="Grading[a] returns an even value if a is regarded as an even (bosonic) field, and an odd value if a is regarded odd (fermionic).";
NormalOrderChangeOrder::"usage"="NormalOrderChangeOrder[a,b] uses quasi-commutativity to express (a\[SmallCircle]b) as (b\[SmallCircle]a) + commutator. Short name is NOCO.";
NormalOrderCommutator::"usage"="NormalOrderCommutator[a,b] calculates a\[SmallCircle]b - (-1)^(a b) b\[SmallCircle]a .";
NormalOrderAssociator::"usage"="NormalOrderAssociator[a,b,c] calculates ((a\[SmallCircle]b)\[SmallCircle]c) - (a\[SmallCircle](b\[SmallCircle]c)) .";
NormalOrderChangeParenthesis::"usage"="NormalOrderChangeParenthesis[expr] uses NormalOrderAssociator to express ((a\[SmallCircle]b)\[SmallCircle]c) or (a\[SmallCircle](b\[SmallCircle]c)) \
by means of the other expression. The expression (a\[SmallCircle]b)\[SmallCircle](c\[SmallCircle]d) is transformed to ((a\[SmallCircle]b)\[SmallCircle]c)\[SmallCircle]d . Short name NOCP.";
NormalOrderChangeParenthesisForward::"usage"="NormalOrderChangeParenthesisForward[expr] transforms an expression \
of the form (a\[SmallCircle]b)\[SmallCircle](c\[SmallCircle]d) to the form  (a\[SmallCircle](b\[SmallCircle](c\[SmallCircle]d)).";
CollectDerivatives::"usage"="CollectDerivatives[expr] tries to use Leibniz rule to write expressions involving \
derivatives more compact. Only works on the top-level of an expression. Short name is CD[expr].";
ExpandDerivatives::"usage"="ExpandDerivatives[expr] use Leibniz rule to expand derivatives. E.g. \[Square](\!\(\*OverscriptBox[\"a\", \"^\"]\)\[SmallCircle]\!\(\*OverscriptBox[\"b\", \"^\"]\)) is expanded to (\!\(\*OverscriptBox[\"a\", \"^\"]\)\[SmallCircle]\[Square]\!\(\*OverscriptBox[\"b\", \"^\"]\))+(\[Square]\!\(\*OverscriptBox[\"a\", \"^\"]\)\[SmallCircle]\!\(\*OverscriptBox[\"b\", \"^\"]\)). \
Short name is ED[expr].";
LambdaBracketJacobiator::"usage"="LambdaBracketJacobiator[a,b,c] calculates the Jacobiator of the Lambda Bracket. It is defined as \
[a Lambda [b Gamma c]] - (-1)^(N(a+1))[[a Lambda b] Gamma+Lambda c] - (-1)^((a+N)(b+N))[b Gamma [a Lambda c]] .";
LambdaBracketHandleIndices::"usage"="LambdaBracketHandleIndices[a,b] calculates [\!\(\*SubscriptBox[\"a\", \"\[Lambda]\"]\)b]. \
First, the dummy indices is replaced with unique names, using MakeDummyIndicesUnique. \
After the calculation, the indices are made canonical, using MakeDummyIndicesCanonical. \
Inputed with the AngleBracket, i.e. \[LeftAngleBracket]a,b\[RightAngleBracket].";
MakeDummyIndicesUnique::"usage"="MakeDummyIndicesUnique[expr] makes repeated indices unique. Short name is MDIU.";
MakeDummyIndicesCanonical::"usage"="MakeDummyIndicesCanonical[expr] renames repeated \
indices by the naming scheme \[Alpha], \[Beta], \[Gamma] etc. Short name is MDIC.";
\[Lambda]::"usage"="This symbol representing various poles in the calculated OPEs. Even.";
\[Chi]::"usage"="This symbol representing various poles in the calculated OPEs. Odd.";
\[Rho]::"usage"="This symbol representing various poles in the calculated OPEs, when calculating the Jacobiator. Even.";
\[Eta]::"usage"="This symbol representing various poles in the calculated OPEs, when calculating the Jacobiator. Odd.";
OddNumericQ::"usage"="OddNumericQ indicates that a variable is odd, e.g. like  \[Chi]. \
Note that SD[\[Chi]]:=2 \[Lambda] , but this is not implemented for a general OddNumericQ  . ";
MakeNormalOrderingCanonical::"usage"="MakeNormalOrderingCanonical[expr] change the \
normal ordering to the scheme (a\[SmallCircle](b\[SmallCircle](c\[SmallCircle] ... ))). Short name is MNOC.";
DoDeltaContractions::"usage"="DoDeltaContractions[expr] performs the possible \
contractions with the special field \!\(\*SubsuperscriptBox[OverscriptBox[\"\[Delta]\", \"^\"], \"\[Alpha]\", \"\[Beta]\"]\) .";
MoveTerm::"usage"="MoveTerm[expr,pos,m] moves the element at position pos of the expression expr m steps";
SortExpression::"usage"="SortExpression[expr, order_List] sorts the expression expr, in the order specified by order. \
The list order as the symbols of the fields as values. E.g. SortExpression[\!\(\*OverscriptBox[\"a\", \"^\"]\)\[SmallCircle]\!\(\*OverscriptBox[\"b\", \"^\"]\), {b,a}] yields \!\(\*OverscriptBox[\"b\", \"^\"]\)\[SmallCircle]\!\(\*OverscriptBox[\"a\", \"^\"]\) + terms from \
moving the fields. If the symbols of the fields are not included in order, alphabetic order are used. If \
SortDerivativesFirst is set to true, terms with derivatives are sorted first, in case of equal symbols, otherwise last.";
SortDerivativesFirst::"usage"="SortDerivativesFirst= False|True sets, in case to fields have the same symbol, whether \
terms with derivatives should be sorted first or not.";
FieldSymmetricUpperIndices::"usage"="FieldSymmetricUpperIndices[fieldsym_Symbol] declares that the field with the \
symbol fieldsym are symmetric in its upper indices.";
FieldAntiSymmetricUpperIndices::"usage"="FieldAntiSymmetricUpperIndices[fieldsym_Symbol] declares that the field \
with the symbol fieldsym are anti-symmetric in its upper indices.";
FieldSymmetricLowerIndices::"usage"="FieldSymmetricLowerIndices[fieldsym_Symbol] declares that the field with the \
symbol fieldsym are symmetric in its lower indices.";
FieldAntiSymmetricLowerIndices::"usage"="FieldAntiSymmetricLowerIndices[fieldsym_Symbol] declares that the field \
with the symbol fieldsym are anti-symmetric in its lower indices.";
DefineComponents::"usage"="DefineComponents[superfieldSym_Symbol,constPart_Symbol,thetaPart_Symbol] defines the \
expansion of the superfield with symbol superfieldSym as Field[constPart,...] + \[Theta] Field[thetaPart,...].";
ExpandSuperFields::"usage"="ExpandSuperFields[expr] expands the superfield-expression expr into components. \
The answer is of the form {{constant part, grading of this part},{theta-part, grading of this part}}";
ExpandDummyIndices::"usage"="ExpandDummyIndices[Expr_, indRange_List] replaces all dummy indices with values from indRange, \
e.g. ExpandDummyIndices[\!\(\*SubscriptBox[OverscriptBox[\"a\", \"^\"], \"i\"]\)\[SmallCircle]\!\(\*SuperscriptBox[OverscriptBox[\"b\", \"^\"], \"i\"]\),{1,2}] gives \!\(\*SubscriptBox[OverscriptBox[\"a\", \"^\"], \"1\"]\)\[SmallCircle]\!\(\*SuperscriptBox[OverscriptBox[\"b\", \"^\"], \"1\"]\)+\!\(\*SubscriptBox[OverscriptBox[\"a\", \"^\"], \"2\"]\)\[SmallCircle]\!\(\*SuperscriptBox[OverscriptBox[\"b\", \"^\"], \"2\"]\). This is useful when given concrete realizations of tensors.";
SetSUSY::"usage"="SetSUSY[True] sets the lambda-bracket to be calculated within the N=1 formalisms. With \
SetSUSY[False], lambda-brackets are calculated without superfields.";
GetSUSY::"usage"="GetSUSY[] returns true, if the lambda brackets are to be calculated in N=1 formalism, and false otherwise";


(*Short names*)
NOCO::usage="NOCO is a short name for NormalOrderChangeOrder";
NOCP::usage="NOCP is a short name for NormalOrderChangeParenthesis";
CD::usage="CD is a short name for CollectDerivatives";
ED::usage="ED is a short name for ExpandDerivatives";
MNOC::usage="MNOC is a short name for MakeNormalOrderingCanonical";
MDIC::usage="MDIC is a short name for MakeDummyIndicesCanonical";
MDIU::usage="MDIU is a short name for MakeDummyIndicesUnique";



(* ::Code:: *)
Begin["`Private`"]; 

(*Short names*)
NOCO = NormalOrderChangeOrder; 
NOCP = NormalOrderChangeParenthesis; 
CD = CollectDerivatives; 
ED = ExpandDerivatives; 
MNOC = MakeNormalOrderingCanonical; 
MDIC = MakeDummyIndicesCanonical; 
MDIU = MakeDummyIndicesUnique; 


(* ::Code:: *)
calcSUSY = True; 
SetSUSY[val:True | False] := Module[{}, calcSUSY = val; ]; 
GetSUSY[] := calcSUSY; 
NumericQ[\[Lambda]] := True;
NumericQ[\[Rho]] := True; 
OddNumericQ[_] := False; 
OddNumericQ[\[Chi]] := True; 
OddNumericQ[\[Eta]] := True; 

\[Chi] /: \[Chi]^(a_) := (-\[Lambda])^Quotient[a, 2]*\[Chi]^Mod[a, 2] /; a > 1; 
(*
\[Eta] /: \[Chi]*\[Eta] := - \[Eta]**\[Chi];
\[Eta] /: Times[a___,\[Chi],b___,\[Eta],c___] := - \[Eta]**\[Chi]*a*b*c;
\[Eta] /: Times[a___,\[Eta],b___,\[Chi],c___] := + \[Eta]**\[Chi]*a*b*c;
*)
TD[(a_)?NumericQ*(b_)] := a*TD[b]; 
TD[(a_)?OddNumericQ*(b_)] := a*TD[b]; 
TD[_?NumericQ] := 0; 
TD[_?NumericQ^_] := 0; 
TD[_?OddNumericQ] := 0; 
TD[_?OddNumericQ^_] := 0; 
TD[a_Plus] := (TD[#1] & ) /@ a; 
SD[(a_)?NumericQ*(b_)] := a*SD[b]; 

(*SD[(a_)?OddNumericQ*(b_)] := (-a)*SD[b] + 2*\[Lambda]*b; *)

(* SD[\[Eta]*(b_)] := (-\[Eta])*SD[b] + 2*\[Rho]*b; *)
SD[\[Chi]*(b_)] := (-\[Chi])*SD[b] + 2*\[Lambda]*b; 


SD[_?NumericQ] := 0; 
SD[_?NumericQ^_] := 0; 
(*SD \[Chi] + \[Chi] SD = 2 \[Lambda] . So when hit on only \[Chi] :   *)
SD[\[Chi]] := 2*\[Lambda]; 
(*SD \[Chi] + \[Chi] SD = 2 \[Lambda] . So when hit on only \[Chi] :   *)
(* SD[\[Eta]] := 2*\[Rho]; *)
SD[a_Plus] := (SD[#1] & ) /@ a; 
SD[SD[a_]] := TD[a]; 
SD[TD[a_]] := TD[SD[a]]; 


(* Default empty lists*)
Field[sym_Symbol ] := Field[sym,{},{},{}];
Field[sym_Symbol ,downindices_List] := Field[sym,downindices,{},{}];
Field[sym_Symbol ,downindices_List, upindices_List] := Field[sym,downindices,upindices,{}];
Field[sym_Symbol ,downindices_List, upindices_List,derivatives_List] := Field[sym,downindices,upindices, Sort[derivatives]]/; !OrderedQ[derivatives];



(* ::Code:: *)
NormalOrder[a_,b_Plus ] := Map[(NormalOrder[a,#])&,b];
NormalOrder[a_Plus,b_] := Map[(NormalOrder[#,b])&,a];

NormalOrder[a_,Times[b_?NumericQ,c_]] := Times[b,NormalOrder[a,c]] ;
NormalOrder[Times[b_?NumericQ,c_],a_] := Times[b,NormalOrder[c,a]];

NormalOrder[a_,Times[b_?OddNumericQ,c_]] := (-1)^(Grading[a]) * b * NormalOrder[a,c] ;
NormalOrder[Times[b_?OddNumericQ,c_],a_] := b * NormalOrder[c,a];


(* ::Code:: *)
NormalOrder[a_?NumericQ,b_]:=a*b;
NormalOrder[a_,b_?NumericQ]:=a*b;
NormalOrder[a_?OddNumericQ,b_]:=a*b;
NormalOrder[a_,b_?OddNumericQ]:=(-1)^Grading[a]*a*b;
(*Propagate -1-terms from eg grading out of normal order*)
NormalOrder[Power[-1,a_]*b_,c_]:= Power[-1,a]*NormalOrder[b,c];
NormalOrder[b_,Power[-1,a_]*c_]:= Power[-1,a]*NormalOrder[b,c];

NormalOrder[a_,SD[b_Plus]]:= Map[(NormalOrder[a,SD[#]])&,b];
NormalOrder[SD[b_Plus],a_]:= Map[(NormalOrder[SD[#],a])&,b];
NormalOrder[a_,TD[b_Plus]]:= Map[(NormalOrder[a,TD[#]])&,b];
NormalOrder[TD[b_Plus],a_]:= Map[(NormalOrder[TD[#],a])&,b];




(* ::Code:: *)
(* Distributive *)
LambdaBracket[a_,b_Plus] := Map[(LambdaBracket[a,#])&,b];
LambdaBracket[a_Plus,b_] := Map[(LambdaBracket[#,b])&,a];

LambdaBracket[a_,Times[b_?NumericQ,c_]] := Times[b,LambdaBracket[a,c]];
LambdaBracket[Times[b_?NumericQ,c_],a_] := Times[b,LambdaBracket[c,a]];

(*Signs: bracket is odd in N=! case ->extra sign when move out odd. See eg 10.1112/S0010437X07003223 , eq 7.4.9 *)
LambdaBracket[a_,Times[b_?OddNumericQ,c_]] :=(-1)^Boole[calcSUSY] (-1)^(Grading[a]) b LambdaBracket[a,c];
LambdaBracket[Times[b_?OddNumericQ,c_],a_] := (-1)^Boole[calcSUSY] b LambdaBracket[c,a];


LambdaBracket[a_?NumericQ,b_] := 0;
LambdaBracket[b_,a_?NumericQ] := 0;
LambdaBracket[a_?OddNumericQ,b_] := 0;
LambdaBracket[b_,a_?OddNumericQ] := 0;



(* Sesquilinearity: *)
LambdaBracket[TD[a_],b_] := -\[Lambda]*LambdaBracket[a,b];
LambdaBracket[a_,TD[b_]] :=Module[{lambdaab},lambdaab = LambdaBracket[a,b]; \[Lambda] * lambdaab + TD[lambdaab ]] 
LambdaBracket[SD[a_],b_] := \[Chi]*LambdaBracket[a,b];
LambdaBracket[a_,SD[b_]] :=Module[{lambdaab},lambdaab = LambdaBracket[a,b];-(-1)^(Grading[a])*( \[Chi] * lambdaab + SD[lambdaab ])] ;



(*  Skew-commutativity *) 
LambdaBracketChangeOrder[a_,b_] := (-(-1)^Boole[calcSUSY]) (-1)^(Grading[a]*Grading[b])( (LambdaBracket[b,a]//Expand)/.  {Times[\[Lambda]^n_, e_] :> Nest[(-\[Lambda]*#-TD[#])&,e,n], Times[\[Lambda], e_]->-Times[\[Lambda], e]-TD[e],\[Lambda]->-\[Lambda]})/. {Times[\[Chi], e_]->-Times[\[Chi], e]-SD[e], \[Chi]->-\[Chi]}; 



(* Quasi-Leibniz *)
LambdaBracket::notevalprop = "The \[CapitalLambda]-bracket `1` is not properly defined.";

LambdaBracket[a_,NormalOrder[b_,c_]] := Module[
	{lambdabracketab,lambdabracketac,lambdabracketabc, tmplambda,tmpchi, lambdaToIntegrateOver,chiToIntegrateOver,integralTerm,ans},NumericQ[tmplambda] := True;
OddNumericQ[tmpchi] := True;
	lambdabracketab=LambdaBracket[a,b]; 
	lambdabracketac=LambdaBracket[a,c];

(*
Print["[a,b*c]"];Print[ {a,b,c}];
*)
(*	
Print["lambdabracketab:"];Print[lambdabracketab];
	Print["lambdabracketac:"];Print[lambdabracketac];
*)
(*Maps \[Chi]-> -tmpchi , assuming the odd integration acts from this way, otherwise, we would get eg another sign on central term in Virasoro*)
	lambdabracketabc = LambdaBracket[lambdabracketab/.{\[Lambda]-> tmplambda,\[Chi]-> -tmpchi}, c]/. {\[Lambda] -> lambdaToIntegrateOver, \[Chi]-> chiToIntegrateOver};
(*	
	Print["lambdabracketabc:"];Print[(lambdabracketabc)];
*)	
	(* Reduce higher powers of odd integration variable using \[Chi]^2 = -\[Lambda] *)
	If[calcSUSY,
		lambdabracketabc =
			FixedPoint[
				Expand[
					# /. chiToIntegrateOver^n_Integer /; n >= 2 :>
						(-lambdaToIntegrateOver)^Quotient[n, 2]*
						chiToIntegrateOver^Mod[n, 2]
				] &,
				Expand[lambdabracketabc]
			]
	];
(*If calcSUSY == True, then only chi-term *)
	integralTerm =  Integrate[Coefficient[lambdabracketabc,chiToIntegrateOver,Boole[calcSUSY]]  , {lambdaToIntegrateOver,0,\[Lambda]}]//Expand;

(*If[
	Length[(integralTerm /. {tmplambda -> \[Lambda], 
              tmpchi -> \[Chi]}) // Coefficient[#, \[Lambda], 1] & // 
          Coefficient[#, \[Chi], 0] &] == 0,
      Print["integralTerm:"]; 
      Print[integralTerm ];
  ];
*)

ans = NormalOrder[lambdabracketab,c] + (-1)^((Grading[a]+Boole[calcSUSY])*Grading[b])*NormalOrder[b,lambdabracketac] +integralTerm /. {tmplambda->\[Lambda],tmpchi->\[Chi]} ;
	If[MemberQ[lambdabracketabc,_LambdaBracket]|| Head[lambdabracketab] === LambdaBracket,Message[LambdaBracket::notevalprop,{lambdabracketab , lambdabracketabc} ]];
	ans];


(* Quasi-Leibniz, using Skew-commutativity *)
(*Print["[b*c,a]"];Print[{b,c,a}];*)
LambdaBracket[NormalOrder[b_,c_], a_] := Module[{},(*Print["[b*c,a]"];Print[{b,c,a}];*) LambdaBracketChangeOrder[NormalOrder[b,c], a]];


LambdaBracketJacobiator[a_,b_,c_]:=Module[{aExpr=MDIU[a],bExpr=MDIU[b],cExpr=MDIU[c],bcBracket,abBracket,acBracket,Expr1,Expr2,Expr3,tmpOdd,tmpEven,tmp\[Chi]},
OddNumericQ[tmpOdd] := True; 
NumericQ[tmpEven] := True; 
(* Part 1 *)
bcBracket=\[LeftAngleBracket]bExpr,cExpr\[RightAngleBracket]/.{\[Chi]->tmpOdd,\[Lambda]->tmpEven};

Expr1=\[LeftAngleBracket]aExpr,bcBracket\[RightAngleBracket]/.tmpEven->\[Rho]/.{tmpOdd*\[Chi]->\[Eta]**\[Chi],tmpOdd->\[Eta]};
(*Print["Expr1"];Print[Expr1];*)
(* Part 2 *)
abBracket=\[LeftAngleBracket]aExpr,bExpr\[RightAngleBracket]/.{\[Chi]->tmpOdd,\[Lambda]->tmpEven};
Expr2=-(-1)^(Boole[GetSUSY[]]*(Grading[aExpr]+1)) (((\[LeftAngleBracket]abBracket,cExpr\[RightAngleBracket]/.{\[Lambda]->(\[Lambda]+\[Rho]),tmpEven->\[Lambda]}//Expand)/.tmpOdd*\[Chi]->(-\[Lambda]-\[Eta]**tmp\[Chi])//Expand)/.{tmpOdd->tmp\[Chi],\[Chi]->(tmp\[Chi]+\[Eta])}//Expand)/.tmp\[Chi]->\[Chi];
(*Print["Expr2"];Print[Expr2];*)
(* Part 3 *)
acBracket=\[LeftAngleBracket]aExpr,cExpr\[RightAngleBracket]/.{\[Chi]->tmpOdd,\[Lambda]->tmpEven};
Expr3=-(-1)^((Boole[GetSUSY[]]+Grading[aExpr])(Boole[GetSUSY[]]+Grading[bExpr]))\[LeftAngleBracket]bExpr,acBracket\[RightAngleBracket]/.{\[Chi]->\[Eta],\[Lambda]->\[Rho]}/.tmpEven->\[Lambda]/.{tmpOdd*\[Eta]->-\[Eta]**\[Chi],tmpOdd->\[Chi]};
(*Print["Expr3"];Print[Expr3];*)
Expr1+Expr2+Expr3]


(*Grading[_] := 0;*)
Grading::notpropergrading="The expression  `1` contains different gradings.";
Grading[NormalOrder[a_,b_]] := Mod[Grading[a] +Grading[b],2];
Grading[TD[a_]] := Grading[a] // Mod[#,2]&;
Grading[SD[a_]]:= 1+ Grading[a] // Mod[#,2]&;
Grading[a_?NumericQ*b_]:=Grading[b];
Grading[a_?OddNumericQ*b_]:=1+Grading[b]// Mod[#,2]&;
Grading[a_?NumericQ]:=0;
Grading[a_?OddNumericQ]:=1;
Grading[list_Plus]:=Module[{gradings=DeleteDuplicates@(Grading/@(List@@list))},If[Length@gradings=!=1,Message[Grading::notpropergrading,list]];First@gradings];




(*Quasi-Commutativity *)
NormalOrderChangeOrder[NormalOrder[a_,b_]] :=  (-1)^(Grading[a]*Grading[b]) NormalOrder[b,a]+ NormalOrderCommutator[a,b] ;
NormalOrderChangeOrder[a_?NumericQ*b_]:= a*NormalOrderChangeOrder[b];
NormalOrderChangeOrder[a_?OddNumericQ*b_]:= a*NormalOrderChangeOrder[b];
NormalOrderChangeOrder[a_Plus]:= NormalOrderChangeOrder/@a;



NormalOrderCommutator[a_,b_] := Module[{tmplambda,startlambda,lambdabracketab = LambdaBracket[a,b],integralTerm},
If[MemberQ[lambdabracketab,_LambdaBracket] || Head[lambdabracketab] === LambdaBracket, Message[LambdaBracket::notevalprop],lambdabracketab];
integralTerm = (Integrate[Coefficient[lambdabracketab,\[Chi],Boole[calcSUSY]]/. \[Lambda]->tmplambda,{tmplambda,startlambda,0}]//Expand) /. Times[startlambda, c_] -> -TD[c] /. Times[startlambda^lambdapower_Integer,c_] :>  (-1)^lambdapower Nest[TD,c,lambdapower ]/. startlambda -> 0;
integralTerm];

(*Quasi-Associativity*)
NormalOrderAssociator[a_,b_,c_] := Module[{tmplambda,LambdaBracketbc, LambdaBracketac,ans},
LambdaBracketbc=LambdaBracket[b,c];
If[Head[LambdaBracketbc] === LambdaBracket,Message[LambdaBracket::notevalprop,LambdaBracketbc]];
LambdaBracketac=LambdaBracket[a,c] ;
If[Head[LambdaBracketac] === LambdaBracket,Message[LambdaBracket::notevalprop,LambdaBracketac]];
ans = ((Integrate[Coefficient[LambdaBracketbc,\[Chi],Boole[calcSUSY]]/.\[Lambda]->tmplambda,{tmplambda,0,tmplambda}]//Expand) /. {Times[tmplambda,bc_] -> NormalOrder[TD[a],bc],Times[tmplambda^d_Integer,bc_] :> NormalOrder[Nest[TD,a,d],bc], tmplambda->NormalOrder[TD[a],1]} )+
(-1)^(Grading[a]*Grading[b])*((Integrate[Coefficient[LambdaBracketac,\[Chi],Boole[calcSUSY]]/.\[Lambda]->tmplambda ,{tmplambda,0,tmplambda}]//Expand)  /. {Times[tmplambda,ac_] -> NormalOrder[TD[b],ac], Times[tmplambda^d_Integer,ac_] :>  NormalOrder[Nest[TD,b, d],ac],tmplambda->NormalOrder[TD[b],1]});ans];

(*NB: Order important: The expression is transformed to (a\[SmallCircle]b)\[SmallCircle](c\[SmallCircle]d) ((a\[SmallCircle]b)\[SmallCircle]c)\[SmallCircle]d  . Important for MakeNormalOrderingCanonical . *)
NormalOrderChangeParenthesis[a_?NumericQ * c_]:=a*NormalOrderChangeParenthesis[c];
NormalOrderChangeParenthesis[NormalOrder[a_,NormalOrder[b_,c_]] ] :=  NormalOrder[NormalOrder[a,b],c] -NormalOrderAssociator[a,b,c];
NormalOrderChangeParenthesis[NormalOrder[NormalOrder[a_,b_],c_] ] :=  NormalOrder[a,NormalOrder[b,c]] +NormalOrderAssociator[a,b,c];

(*If not two NormalOrders, then do nothing*)
NormalOrderChangeParenthesis[expr:NormalOrder[a_,b_]] :=  expr;

NormalOrderChangeParenthesisForward[NormalOrder[NormalOrder[a_,b_],NormalOrder[c_,d_]]]:=NormalOrder[a,NormalOrder[b,NormalOrder[c,d]]]+NormalOrderAssociator[a,b,NormalOrder[c,d]];


(* CollectDerivatives *)
(*Only works on the first level. Needs to be rewitten in a better way, in order to catch terms at lower levels.*)

(*

CollectDerivatives[]:=0;
*)
(*CDtmpvar : dymmyvariable that is used in CollectDerivatives and then put to 1*)
CollectDerivatives[a_]:=(CDtmpvar*a//Expand//CollectDerivativesInt)/.CDtmpvar->1;


(*
CollectDerivativesInt[a_?NumericQ] := a;
CollectDerivativesInt[a_?NumericQ*b_] := a*CollectDerivativesInt[b];
CollectDerivativesInt[a_?OddNumericQ] := a;
CollectDerivativesInt[a_?OddNumericQ*b_] := a*CollectDerivativesInt[b];
*)

(*S ( Ta b) = TSa b +/-  Ta Sb *)
CollectDerivativesInt[Plus[f___, c_*NormalOrder[TD[SD[a_]],b_],g___, d_* rest:NormalOrder[TD[a_],SD[b_]], e___]] :=CollectDerivativesInt[f+g+e+(d-(-1)^Grading[a]*c)* rest ] +c* SD[NormalOrder[TD[a],b]]/;Abs[(d-(-1)^Grading[a]*c)/d]<1       ; 


(*S ( a Tb) = Sa Tb +/-  a TSb *)
CollectDerivativesInt[Plus[f___, c_*NormalOrder[SD[a_],TD[b_]],g___, d_* rest:NormalOrder[a_,TD[SD[b_]]], e___]] :=CollectDerivativesInt[f+g+e+(d-(-1)^Grading[a]*c)* rest ] +c* SD[NormalOrder[a,TD[b]]]/;Abs[(d-(-1)^Grading[a]*c)/d]<1       ; 


(*S (a b) = Sa b +/- a Sb *)
CollectDerivativesInt[Plus[f___, c_*NormalOrder[SD[a_],b_],g___, d_* rest:NormalOrder[a_,SD[b_]], e___]] :=CollectDerivativesInt[f+g+e+(d-(-1)^Grading[a]*c)* rest ] +c* SD[NormalOrder[a,b]]/;Abs[(d-(-1)^Grading[a]*c)/d]<1      ; 


(*S ( Sa b) = Ta b +/- S a Sb *)
CollectDerivativesInt[Plus[f___, c_*NormalOrder[TD[a_],b_],g___, d_* rest:NormalOrder[SD[a_],SD[b_]], e___]] :=CollectDerivativesInt[f+g+e+(d-(-1)^Grading[SD[a]]*c)* rest ] +c* SD[NormalOrder[SD[a],b]]/;Abs[(d-(-1)^Grading[SD[a]]*c)/d]<1      ; 

(*S ( a Sb) = Sa Sb +/-  a Tb *)
CollectDerivativesInt[Plus[f___, c_*NormalOrder[a_,TD[b_]],g___, d_* rest:NormalOrder[SD[a_],SD[b_]], e___]] :=CollectDerivativesInt[f+g+e+(d-(-1)^Grading[a]*c)* rest ] +c* SD[NormalOrder[a,SD[b]]]/;Abs[(d-(-1)^Grading[a]*c)/d]<1     ; 


(*S ( a Sb) = Sa Sb +/-  a Tb *)
CollectDerivativesInt[Plus[f___, c_*NormalOrder[a_,TD[b_]],g___, d_* rest:NormalOrder[SD[a_],SD[b_]], e___]] :=CollectDerivativesInt[f+g+e+(d-(-1)^Grading[a]*c)*rest ] +c* SD[NormalOrder[a,SD[b]]]/;Abs[(d-(-1)^Grading[a]*c)/d]<1;

(*S ( Sa Sb) = Ta Sb +/-  Sa Tb *)
CollectDerivativesInt[Plus[f___, c_*NormalOrder[TD[a_],SD[b_]],g___, d_* rest:NormalOrder[SD[a_],TD[b_]], e___]] :=CollectDerivativesInt[f+g+e+(d-(-1)^Grading[SD[a]]*c)*rest ] +c* SD[NormalOrder[SD[a],SD[b]]]/;Abs[(d-(-1)^Grading[SD[a]]*c)/d]<1; 



(*T (a b) = Ta b + a Tb*)
CollectDerivativesInt[Plus[f___, c_*NormalOrder[TD[a_],b_],g___, d_* rest:NormalOrder[a_,TD[b_]], e___]] :=CollectDerivativesInt[f+g+e+(d-c)* rest ] +c* TD[NormalOrder[a,b]]/;Abs[(d-c)/d]<1; 




CollectDerivativesInt[a_] := a;







ExpandDerivatives[a_?NumericQ] := a;
ExpandDerivatives[a_?NumericQ*b_] := a*ExpandDerivatives[b];
ExpandDerivatives[a_?OddNumericQ] := a;
ExpandDerivatives[a_?OddNumericQ*b_] := a*ExpandDerivatives[b];
ExpandDerivatives[a_Plus] := Map[ExpandDerivatives,a];
ExpandDerivatives[TD[a_Plus]] := Map[(TD[ExpandDerivatives[#]])&,a];
ExpandDerivatives[SD[a_Plus]] := Map[(SD[ExpandDerivatives[#]])&,a];
ExpandDerivatives[a_Field] :=a;
ExpandDerivatives[TD[NormalOrder[a_,b_]]]:=NormalOrder[ExpandDerivatives[TD[a]],ExpandDerivatives[b]] + NormalOrder[ExpandDerivatives[a],ExpandDerivatives[TD[b]]];
ExpandDerivatives[SD[NormalOrder[a_,b_]]]:=NormalOrder[ExpandDerivatives[SD[a]],ExpandDerivatives[b]] + (-1)^Grading[a]* NormalOrder[ExpandDerivatives[a],ExpandDerivatives[SD[b]]];
ExpandDerivatives[TD[a_]] :=TD[ExpandDerivatives[a]];
ExpandDerivatives[SD[a_]] :=SD[ExpandDerivatives[a]];
ExpandDerivatives[NormalOrder[a_,b_]]:=NormalOrder[ExpandDerivatives[a],ExpandDerivatives[b]];


(*tmp solution*)
ExpandDerivatives[MoveTermRight[a_,pos_]]:= MoveTermRight[ExpandDerivatives[a],pos];


(* Format the output *)
(*
T/:MakeBoxes[T[a_],StandardForm] := RowBox[{SubscriptBox["\[PartialD]","\[Xi]"],MakeBoxes[a,StandardForm]}] ; *)

LambdaBracket/:MakeBoxes[LambdaBracket[a_,b_],StandardForm]:=RowBox[{"\[LeftAngleBracket]",MakeBoxes[a,StandardForm],",",MakeBoxes[b,StandardForm],"\[RightAngleBracket]"}] ;


AngleBracket[a_,b_] := LambdaBracketHandleIndices[a,b];



TD/: MakeBoxes[TD[a_],StandardForm]:=RowBox[{"\[Square]",RowBox[{MakeBoxes[a,StandardForm]}]}];

(*
MakeExpression[RowBox[{"\[PartialD]",expr___}],g_] :=MakeExpression[RowBox[{"TD[",expr,"]"}],g];
*)

SD/: MakeBoxes[SD[a_],StandardForm]:=RowBox[{"\[Del]",RowBox[{MakeBoxes[a,StandardForm]}]}];

(*MakeExpression[RowBox[{"D",expr___}],g_] :=MakeExpression[RowBox[{"SD[",expr,"]"}],g];*)

Square[expr_]:= TD[expr];
Del[expr_]:= SD[expr];


SmallCircle[ a_,b_] :=NormalOrder[a,b];

(*If no parenthesis is written out, assuming (a b) c) d) ...*)
SmallCircle[ a_,b_,c__] :=SmallCircle[NormalOrder[a,b],c];

NormalOrder /:  MakeBoxes[NormalOrder[a_,b_,___],StandardForm]:=RowBox[{"(",MakeBoxes[a,StandardForm],"\[SmallCircle]",MakeBoxes[b,StandardForm],")"}];
(*
MakeExpression[RowBox[{expr1___,"\[SmallCircle]",expr2___}],g_] :=MakeExpression[RowBox[{"NormalOrder[",expr1,",",expr2,"]"}],g];
*)


ExtractIndicesFromBox[box_] := Module[{indices,pos,posTmp},indices = {box} /. RowBox -> List // Flatten;
 posTmp =( Position[indices , "," ]//Flatten); If[ Length[posTmp] === 0, pos=0,pos = posTmp[[1]]]  ;If[pos === 0, {indices,{}}, {Take[indices,pos-1],
Drop[indices,pos]}]];

MakeExpression[OverscriptBox[sym_,"^"],g_] := MakeExpression[RowBox[{"Field[",sym,",{},{},{}]"}],g];

MakeExpression[SubsuperscriptBox[OverscriptBox[sym_,"^"],down_,up_],g_]:=Module[{downInd, upInd,derivInd,unused},
	{downInd, derivInd} = ExtractIndicesFromBox[down];{upInd, unused} = ExtractIndicesFromBox[up];
	MakeExpression[RowBox[{"Field[",sym,",",(MakeExpression[#,g])& /@ downInd//ReleaseHold,"," , (MakeExpression[#,g])& /@upInd//ReleaseHold, ",", (MakeExpression[#,g])& /@derivInd//ReleaseHold, "]"}],g]
	];

MakeExpression[SubscriptBox[OverscriptBox[sym_,"^"],down_],g_]:=Module[{downInd,derivInd},
	{downInd, derivInd} = ExtractIndicesFromBox[down];
	MakeExpression[RowBox[{"Field[",sym,",",(MakeExpression[#,g])& /@downInd //ReleaseHold,",{},", (MakeExpression[#,g])& /@derivInd//ReleaseHold, "]"}],g]
	];

MakeExpression[SuperscriptBox[OverscriptBox[sym_,"^"],up_],g_]:=Module[{ upInd,unused},
	{upInd, unused} = ExtractIndicesFromBox[up];MakeExpression[RowBox[{"Field[",sym,",{}," , (MakeExpression[#,g])& /@upInd//ReleaseHold, ",{}]"}],g]
	];
Field /: MakeBoxes[Field[sym_Symbol,{},{},{}],StandardForm] :=  OverscriptBox[MakeBoxes[sym,StandardForm],"^"];

Field /: MakeBoxes[Field[sym_Symbol,{},upindices_List,{}],StandardForm] :=SuperscriptBox[  OverscriptBox[MakeBoxes[sym,StandardForm],"^"],RowBox[{ RowBox[MyRiffle[(ToBoxes[#, StandardForm])&/@ upindices," "]]}]];

Field /: MakeBoxes[Field[sym_Symbol,downindices_List,{},{}],StandardForm] :=SubscriptBox[  OverscriptBox[MakeBoxes[sym,StandardForm],"^"],RowBox[{ RowBox[MyRiffle[(ToBoxes[#, StandardForm])&/@ downindices," "]]}]];

Field /: MakeBoxes[Field[sym_Symbol,downindices_List,{},derivatives_List],StandardForm] :=SubscriptBox[  OverscriptBox[MakeBoxes[sym,StandardForm],"^"],RowBox[{ RowBox[MyRiffle[(ToBoxes[#, StandardForm])&/@ downindices," "]],",",RowBox[MyRiffle[(ToBoxes[#, StandardForm])&/@derivatives," "]]}]];

Field /: MakeBoxes[Field[sym_Symbol,downindices_List,upindices_List,{}],StandardForm] :=SubsuperscriptBox[  OverscriptBox[MakeBoxes[sym,StandardForm],"^"],RowBox[{ RowBox[MyRiffle[(ToBoxes[#, StandardForm])&/@ downindices," "]]}],RowBox[{ RowBox[MyRiffle[(ToBoxes[#, StandardForm])&/@ upindices," "]]}]];

Field /: MakeBoxes[Field[sym_Symbol,downindices_List,upindices_List,derivatives_List],StandardForm] :=SubsuperscriptBox[  OverscriptBox[MakeBoxes[sym,StandardForm],"^"],RowBox[{ RowBox[MyRiffle[(ToBoxes[#, StandardForm])&/@ downindices, " "]],",",RowBox[MyRiffle[(ToBoxes[#, StandardForm])&/@derivatives," "]]}],RowBox[{ RowBox[MyRiffle[(ToBoxes[#, StandardForm])&/@ upindices," "]]}]];




(*Riffle is new in v .6, want code to work in v .5*)
MyRiffle[{a_,c___},elem_] := Join[{a,elem},MyRiffle[{c},elem]];
MyRiffle[{a_},_]:={a};
MyRiffle[{},_]:={};




FieldSymmetricUpperIndices[_Symbol]:= False;
FieldAntiSymmetricUpperIndices[_Symbol]:= False;
FieldSymmetricLowerIndices[_Symbol]:= False;
FieldAntiSymmetricLowerIndices[_Symbol]:= False;


NormalOrder[f1:Field[sym1_Symbol,{___,ind1_,___,ind2_,___},___],f2:Field[sym2_Symbol,_List,{___,ind1_,___,ind2_,___}, ___]] := 0/; FieldAntiSymmetricLowerIndices[sym1] && FieldSymmetricUpperIndices[sym2];

NormalOrder[f2:Field[sym2_Symbol,_List,{___,ind1_,___,ind2_,___}, ___],f1:Field[sym1_Symbol,{___,ind1_,___,ind2_,___},___]] := 0/; FieldAntiSymmetricLowerIndices[sym1] && FieldSymmetricUpperIndices[sym2];

NormalOrder[f1:Field[sym1_Symbol,{___,ind1_,___,ind2_,___},___],f2:Field[sym2_Symbol,_List,{___,ind1_,___,ind2_,___}, ___]] := 0/; FieldSymmetricLowerIndices[sym1] && FieldAntiSymmetricUpperIndices[sym2];

NormalOrder[f2:Field[sym2_Symbol,_List,{___,ind1_,___,ind2_,___}, ___],f1:Field[sym1_Symbol,{___,ind1_,___,ind2_,___},___]] := 0/; FieldSymmetricLowerIndices[sym1] && FieldAntiSymmetricUpperIndices[sym2];


Field[sym_Symbol ,downindices_List, upindices_List,derivatives_List] := Signature[downindices] * Field[sym,Sort[downindices],upindices, derivatives]/; ( FieldAntiSymmetricLowerIndices[sym]&&!OrderedQ[downindices]&&!MemberQ[downindices,_Pattern]);
Field[sym_Symbol ,downindices_List, upindices_List,derivatives_List] :=  Field[sym,Sort[downindices],upindices, derivatives]/; ( FieldSymmetricLowerIndices[sym]&&!OrderedQ[downindices]&&!MemberQ[downindices,_Pattern]);
Field[sym_Symbol,downindices_List, upindices_List,derivatives_List] :=  Signature[upindices] * Field[sym,downindices,Sort[upindices], derivatives]/; ( FieldAntiSymmetricUpperIndices[sym] &&!OrderedQ[upindices]&&!MemberQ[upindices,_Pattern]);
Field[sym_Symbol,downindices_List, upindices_List,derivatives_List] :=  Field[sym,downindices,Sort[upindices], derivatives]/; ( FieldSymmetricUpperIndices[sym] &&!OrderedQ[upindices]&&!MemberQ[upindices,_Pattern]);




Field[sym_Symbol ,downindices_List, upindices_List,derivatives_List] :=0/; ( FieldAntiSymmetricLowerIndices[sym]&&Length@Union[downindices]!=Length[downindices]);
Field[sym_Symbol ,downindices_List, upindices_List,derivatives_List] :=0/; ( FieldAntiSymmetricUpperIndices[sym]&&Length@Union[upindices]!=Length[upindices]);



(*Only selects indicies that are not numeric *)
CollectIndices[Field[_Symbol,downInd_List,upInd_List, deriv_List],down_List,up_List]:={ Join[Select[Join[downInd,deriv],Not[NumericQ[#]]&],down], Join[Select[upInd,Not[NumericQ[#]]&],up]};
CollectIndices[NormalOrder[a_,b_],down_List,up_List]:=Module[{aIndDown, aIndUp,bIndDown, bIndUp}, {aIndDown, aIndUp} = CollectIndices[a]; {bIndDown, bIndUp} = CollectIndices[b]; {Join[aIndDown, bIndDown, down],Join[aIndUp, bIndUp, up]}];
CollectIndices[a_] := CollectIndices[a,{},{}];
CollectIndices[TD[a_],down_List,up_List]:= CollectIndices[a,down,up];
CollectIndices[SD[a_],down_List,up_List]:= CollectIndices[a,down,up];
CollectIndices[a_?NumericQ,down_List,up_List]:={down,up};
CollectIndices[Times[a_?NumericQ,b_],down_List,up_List] :=CollectIndices[b,down,up];
CollectIndices[a_?OddNumericQ,down_List,up_List]:={down,up};
CollectIndices[Times[a_?OddNumericQ,b_],down_List,up_List] :=CollectIndices[b,down,up];

ReplaceIndices[a_,{}]:=a;
ReplaceIndices[Field[sym_Symbol,downInd_List,upInd_List, deriv_List],repRule_]:= Field[sym,downInd/.repRule,upInd/.repRule, deriv/.repRule];
ReplaceIndices[TD[a_],repRule_]:= TD[ReplaceIndices[a,repRule]];
ReplaceIndices[SD[a_],repRule_]:= SD[ReplaceIndices[a,repRule]];
ReplaceIndices[NormalOrder[a_,b_],repRule_] := NormalOrder[ReplaceIndices[a, repRule],ReplaceIndices[b, repRule]];



ExpandDummyIndicesInt[a_, indRange_List]:=Module[{dummyInd,down,up,ReplacementRules},{down,up} = CollectIndices[a];dummyInd = Intersection[down,up];ReplacementRules = Map[MapIndexed[(dummyInd[[First[#2]]]->#)&,#]&,Tuples[indRange,Length[dummyInd]]];Plus@@Map[ReplaceIndices[a,#]&  ,ReplacementRules]   ];
ExpandDummyIndicesInt[a_Plus, indRange_List] :=  Map[(ExpandDummyIndicesInt[#,indRange])&,a];
ExpandDummyIndicesInt[Times[a_?NumericQ,b_], indRange_List] :=Times[a, ExpandDummyIndicesInt[b,indRange]];
ExpandDummyIndicesInt[Times[a_?OddNumericQ,b_], indRange_List] :=Times[a, ExpandDummyIndicesInt[b,indRange]];


ExpandDummyIndices[a_,_]:=a;
ExpandDummyIndices[NormalOrder[a_,b_], indRange_List]:=ExpandDummyIndicesInt[NormalOrder[ExpandDummyIndices[a, indRange],ExpandDummyIndices[b, indRange]], indRange];


ExpandDummyIndices[a_Plus, indRange_List] :=  Map[(ExpandDummyIndices[#,indRange])&,a];

ExpandDummyIndices[Times[a_?NumericQ,b_], indRange_List] :=Times[a, ExpandDummyIndices[b,indRange]];
ExpandDummyIndices[Times[a_?OddNumericQ,b_], indRange_List] :=Times[a, ExpandDummyIndices[b,indRange]];



MakeDummyIndicesUnique[a_]:=Module[{dummyInd,down,up},{down,up} = CollectIndices[a];dummyInd = Intersection[down,up];ReplaceIndices[a,Map[(# -> Unique[#])&,dummyInd]]    ];
MakeDummyIndicesUnique[a_Plus] :=  Map[(MakeDummyIndicesUnique[#])&,a];

MakeDummyIndicesUnique[SD[a_Plus]] :=  SD[Map[(MakeDummyIndicesUnique[#])&,a]];
MakeDummyIndicesUnique[TD[a_Plus]] :=  TD[Map[(MakeDummyIndicesUnique[#])&,a]];

MakeDummyIndicesUnique[Times[a_?NumericQ,b_]] :=Times[a, MakeDummyIndicesUnique[b]];
MakeDummyIndicesUnique[Times[a_?OddNumericQ,b_]] :=Times[a, MakeDummyIndicesUnique[b]];

MakeDummyIndicesCanonical[a_]:=Module[{dummyInd,down,up}, 
	{down,up} = CollectIndices[a];
	dummyInd = Select[up,MemberQ[down,#]&];
ReplaceIndices[a,MapIndexed[(#1 -> Symbol[""<> FromCharacterCode[#2+944]])&,dummyInd]]    ]; (*96 char code for a*)
MakeDummyIndicesCanonical[a_Plus] :=  Map[(MakeDummyIndicesCanonical[#])&,a];

MakeDummyIndicesCanonical[SD[a_Plus]] :=  SD[Map[(MakeDummyIndicesCanonical[#])&,a]];
MakeDummyIndicesCanonical[TD[a_Plus]] :=  TD[Map[(MakeDummyIndicesCanonical[#])&,a]];

MakeDummyIndicesCanonical[Times[a_?NumericQ,b_]] :=Times[a, MakeDummyIndicesCanonical[b]];
MakeDummyIndicesCanonical[Times[a_?OddNumericQ,b_]] :=Times[a, MakeDummyIndicesCanonical[b]];

MakeNormalOrderingCanonicalInt[a_Field]:=a;
MakeNormalOrderingCanonicalInt[NormalOrder[a_,NormalOrder[b_,c_]] ] :=NormalOrderChangeParenthesis[NormalOrder[a,NormalOrder[b,c]]]//MakeNormalOrderingCanonicalInt; 
MakeNormalOrderingCanonicalInt[NormalOrder[NormalOrder[a_,b_],c_]]:=NormalOrder[  MakeNormalOrderingCanonicalInt[NormalOrder[a,b]],  MakeNormalOrderingCanonicalInt[c] ];

(*
MakeNormalOrderingCanonicalInt[NormalOrder[NormalOrder[a_,b_],NormalOrder[c_,d_]] ] :=aa ;
*) 
MakeNormalOrderingCanonicalInt[a_Plus ] := Map[(MakeNormalOrderingCanonicalInt[#])&,a]; 
MakeNormalOrderingCanonicalInt[NormalOrder[a_,b_]]:=NormalOrder[MakeNormalOrderingCanonicalInt[a],MakeNormalOrderingCanonicalInt[b]];
MakeNormalOrderingCanonicalInt[a_Times ] := Map[(MakeNormalOrderingCanonicalInt[#])&,a]; 
MakeNormalOrderingCanonicalInt[a_?NumericQ] := a;
MakeNormalOrderingCanonicalInt[a_?OddNumericQ] := a;
MakeNormalOrderingCanonicalInt[TD[a_]] := TD[MakeNormalOrderingCanonicalInt[a]];
MakeNormalOrderingCanonicalInt[SD[a_]] := SD[MakeNormalOrderingCanonicalInt[a]];
MakeNormalOrderingCanonical[a_] := FixedPoint[MakeNormalOrderingCanonicalInt,a];



CollectDeltaIndices[a_] := CollectDeltaIndices[a,{},{}];
CollectDeltaIndices[Field[Global`\[Delta],downInd_List,upInd_List, deriv_List],down_List,up_List]:={Join[downInd,deriv,down], Join[upInd,up]};
CollectDeltaIndices[Field[_Symbol,___],down_List,up_List]:={down,up};
CollectDeltaIndices[NormalOrder[a_,b_],down_List,up_List]:=Module[{aIndDown, aIndUp,bIndDown, bIndUp}, {aIndDown, aIndUp} = CollectDeltaIndices[a]; {bIndDown, bIndUp} = CollectDeltaIndices[b]; {Join[aIndDown, bIndDown, down],Join[aIndUp, bIndUp, up]}];
CollectDeltaIndices[TD[a_],down_List,up_List]:= CollectDeltaIndices[a,down,up];
CollectDeltaIndices[SD[a_],down_List,up_List]:= CollectDeltaIndices[a,down,up];
CollectDeltaIndices[a_?NumericQ,down_List,up_List]:={down,up};
CollectDeltaIndices[Times[a_?NumericQ,b_],down_List,up_List] :=CollectDeltaIndices[b,down,up];

CollectDeltaIndices[a_?OddNumericQ,down_List,up_List]:={down,up};
CollectDeltaIndices[Times[a_?OddNumericQ,b_],down_List,up_List] :=CollectDeltaIndices[b,down,up];


ApplyRulesToIndices[a_?NumericQ,downrules_List,uprules_List] := a;
ApplyRulesToIndices[a_?NumericQ*b_,downrules_List,uprules_List] := a*ApplyRulesToIndices[b,downrules,uprules];

ApplyRulesToIndices[a_?OddNumericQ,downrules_List,uprules_List] := a;
ApplyRulesToIndices[a_?OddNumericQ*b_,downrules_List,uprules_List] := a*ApplyRulesToIndices[b,downrules,uprules];

ApplyRulesToIndices[a_Plus,downrules_List,uprules_List] := Map[ApplyRulesToIndices,a,downrules,uprules];
ApplyRulesToIndices[TD[a_],downrules_List,uprules_List] := TD[ApplyRulesToIndices[a,downrules,uprules]];
ApplyRulesToIndices[SD[a_],downrules_List,uprules_List] := SD[ApplyRulesToIndices[a,downrules,uprules]];
ApplyRulesToIndices[NormalOrder[a_,b_]  ,downrules_List,uprules_List]:= NormalOrder[
	ApplyRulesToIndices[a,downrules,uprules],
	ApplyRulesToIndices[b,downrules,uprules]];
ApplyRulesToIndices[Field[sym_,downInd_List,upInd_List, deriv_List],downrules_,uprules_]:= Field[sym,downInd/. downrules,upInd /.uprules, deriv/. downrules];


RemoveFields[a_?NumericQ,___] := a;
RemoveFields[a_?OddNumericQ,___] := a;
RemoveFields[a_Plus,downIndRemoved_List,upIndRemoved_List] := Map[RemoveFields[#,downIndRemoved,upIndRemoved]&,a];
RemoveFields[a_Times,downIndRemoved_List,upIndRemoved_List] := Map[RemoveFields[#,downIndRemoved,upIndRemoved]&,a];
RemoveFields[TD[a_],downIndRemoved_List,upIndRemoved_List] := TD[RemoveFields[a,downIndRemoved,upIndRemoved]];
RemoveFields[SD[a_],downIndRemoved_List,upIndRemoved_List] := SD[RemoveFields[a,downIndRemoved,upIndRemoved]];

RemoveFields[Field[sym_Symbol,downInd_List,upInd_List, derivInd_List, rest___], downIndRemoved_List,upIndRemoved_List]:=1/;Intersection[downInd,downIndRemoved] =!= {}||Intersection[derivInd,downIndRemoved] =!= {} ||Intersection[upInd,upIndRemoved] =!= {} ;
RemoveFields[a_Field, ___] :=a;
RemoveFields[NormalOrder[a_,b_] , downIndRemoved_List,upIndRemoved_List] := NormalOrder[RemoveFields[a , downIndRemoved,upIndRemoved] ,RemoveFields[b , downIndRemoved,upIndRemoved] ];

(*
DoDeltaContractions[NormalOrder[ Field[Global`\[Delta],downInd_List,upInd_List, rest___]  ,expr_]  ,downrules_,uprules_ ]:=Module[{},
		DoDeltaContractions[expr  ,downrules,uprules ]
	];/;((downInd =!=(downInd/.uprules)) ||  (upInd =!= (upInd/. downrules)));

DoDeltaContractions[NormalOrder[expr_, Field[Global`\[Delta],downInd_List,upInd_List, rest___]]  ,downrules_,uprules_ ]:=Module[{},
		DoDeltaContractions[expr  ,downrules,uprules ]
	];/;((downInd =!=(downInd/.uprules)) ||  (upInd =!= (upInd/. downrules)));

*)


ApplySequenceReplacement[{}]:={};
ApplySequenceReplacement[{a_Rule}]:={a};
ApplySequenceReplacement[{a_Rule, rest___}]:=  Join[{a}, ApplySequenceReplacement[{rest}]/.a]








DoDeltaContractions[a_Plus] := Map[DoDeltaContractions,a];
(*
DoDeltaContractions[SD[a_Plus]] := SD[Map[DoDeltaContractions,a]];
DoDeltaContractions[TD[a_Plus]] := TD[Map[DoDeltaContractions,a]];
*)
DoDeltaContractions[a_?NumericQ * b_] := a DoDeltaContractions[b];
DoDeltaContractions[a_?OddNumericQ * b_] := a DoDeltaContractions[b];

DoDeltaContractions[expr_] :=Module[
	{down,up,dummyInd, deltInd,deltIndDown,deltIndUp,posUp,downFromInd,downToInd,upFromInd,upToInd,downRules,posDown,upRules,numberofRules,ans},
{down,up} = CollectIndices[expr];
dummyInd = Select[up,MemberQ[down,#]&];
deltInd = CollectDeltaIndices[expr];

deltIndDown =deltInd[[1]];
deltIndUp =deltInd[[2]];

(*Create replacement rules for lower indices*)
posUp=Position[deltIndUp,Alternatives@@dummyInd];(* Which delta-indices that are dummy indices*)

(*
Print["dummyInd"];Print[dummyInd];


Print["deltInd"];Print[deltInd];

Print["deltIndDown"];Print[deltIndDown];
Print["deltIndUp"];Print[deltIndUp];

Print["posUp"];Print[posUp];
*)
downFromInd = Extract[deltIndUp,posUp];
downToInd = Extract[deltIndDown,posUp];
downRules = MapIndexed[(Rule[Extract[downFromInd,#2],#1]&), downToInd]//ApplySequenceReplacement;
(*
Print["deltIndUp"];Print[deltIndUp];
Print["deltIndDown"];Print[deltIndDown];
*)
deltIndUp = Delete[deltIndUp, posUp];
deltIndDown = Delete[deltIndDown, posUp]/.downRules;



(*Create replacement rules for upper indices*)
posDown=Position[deltIndDown,Alternatives@@dummyInd];

upFromInd = Extract[deltIndDown,posDown];
upToInd = Extract[deltIndUp,posDown];
upRules = MapIndexed[(Rule[Extract[upFromInd,#2],#1]&), upToInd]//ApplySequenceReplacement;


numberofRules = Length[downRules] + Length[upRules];
(*

Print["downFromInd"];Print[downFromInd];
Print["downToInd"];Print[downToInd];
Print["downRules"];Print[downRules];

Print["deltIndUp"];Print[deltIndUp];
Print["deltIndDown"];Print[deltIndDown];

Print["upFromInd"];Print[upFromInd];
Print["upToInd"];Print[upToInd];


Print["upRules"];Print[upRules];


Print[RemoveFields[ans,upFromInd,downFromInd]];
*)
ans= ApplyRulesToIndices[expr,downRules,upRules];
(*
Print["expr"];Print[expr];
Print["ApplyRulesToIndices"];Print[ans];


*)

ans= RemoveFields[ ans  ,upFromInd,downFromInd];
(*
If[numberofRules>1,Return[DoDeltaContractions[ans]], Return[ans]];
*)

ans
];



LambdaBracketHandleIndices[a_,b_] := Module[{tmp},
	tmp= LambdaBracket[MakeDummyIndicesUnique[a],MakeDummyIndicesUnique[b]]  ;
	tmp//DoDeltaContractions//MakeDummyIndicesCanonical//Expand ];
(*//(Collect[#,{\[Lambda],\[Chi],\[HBar]},Simplify]&)*)


LengthOfExpression[a_Field] := 1;
LengthOfExpression[NormalOrder[a_,b_]]:=LengthOfExpression[a] + LengthOfExpression[b];
LengthOfExpression[a_?NumericQ *b_] := LengthOfExpression[b];
LengthOfExpression[Power[-1,a_]*b_] := LengthOfExpression[b];
(*
LengthOfExpression[T[a_]] := LengthOfExpression[a];
*)
LengthOfExpression[TD[a_]] := 1;
LengthOfExpression[SD[a_]] := 1;



MoveTerm::notCorrectPosition ="Not a correct position: `1`  `2`";

MoveTerm::changedForm ="The expression changed form: (`1`)\[SmallCircle](`2`)=`3`";

(*
MoveTermRight[a_Plus,pos_Integer ] := Map[(MoveTermRight[#,pos])&,a];
*)
(*How to handle T[T[T[]]] etc ???  *)
MoveTermRight[a_?NumericQ * b_,pos_Integer ]:= a*MoveTermRight[b,pos ];
MoveTermRight[a_?OddNumericQ * b_,pos_Integer ]:= a*MoveTermRight[b,pos ];
MoveTermRight[Power[-1,a_]*b_,pos_Integer] := Power[-1,a]*MoveTermRight[b,pos];
MoveTermRight[a_Field,pos_Integer]:=Module[{},Message[MoveTerm::notCorrectPosition,a,pos];{a,0}];

MoveTermRight[NormalOrder[a_Field,b_Field],pos_Integer]:=Module[{},Message[MoveTerm::notCorrectPosition,NormalOrder[a,b],pos ];{NormalOrder[a,b],0}];


MoveTermRight[ NormalOrder[a_Field, b_Field], 1] := {(-1)^(Grading[a]*Grading[b])NormalOrder[b,a] , MoveCom[a,b]};
MoveTermRight[ NormalOrder[TD[a_], b_Field], 1] := {(-1)^(Grading[a]*Grading[b])NormalOrder[b,TD[a]] , MoveCom[TD[a],b]};
MoveTermRight[ NormalOrder[a_Field, TD[b_]], 1] := {(-1)^(Grading[a]*Grading[b])NormalOrder[TD[b],a] , MoveCom[a,TD[b]]};
MoveTermRight[ NormalOrder[TD[a_], TD[b_]], 1] := {(-1)^(Grading[a]*Grading[b])NormalOrder[TD[b],TD[a]] , MoveCom[TD[a],TD[b]]};

MoveTermRight[ NormalOrder[a:SD[_], b_Field], 1] := {(-1)^(Grading[a]*Grading[b])NormalOrder[b,a] , MoveCom[a,b]};
MoveTermRight[ NormalOrder[a_Field, b:SD[_]], 1] := {(-1)^(Grading[a]*Grading[b])NormalOrder[b,a] , MoveCom[a,b]};
MoveTermRight[ NormalOrder[a:SD[_], b:SD[_]], 1] := {(-1)^(Grading[a]*Grading[b])NormalOrder[b,a] , MoveCom[a,b]};

MoveTermRight[ NormalOrder[a:SD[_], b:TD[_]], 1] := {(-1)^(Grading[a]*Grading[b])NormalOrder[b,a] , MoveCom[a,b]};
MoveTermRight[ NormalOrder[a:TD[_], b:SD[_]], 1] := {(-1)^(Grading[a]*Grading[b])NormalOrder[b,a] , MoveCom[a,b]};


MoveTermRight[ NormalOrder[a_, NormalOrder[b_,c_]] , pos_Integer] := Module[{aLength,bLength,cLength,retExpr,retTail,normOrderab},
	(*Print["Tjo"];*)
	aLength=LengthOfExpression[a];
	bLength=LengthOfExpression[b];
	cLength=LengthOfExpression[c];

	If[pos>aLength,{retExpr, retTail}=MoveTermRight[ NormalOrder[b,c] , pos-aLength];Return[{ NormalOrder[a,retExpr ],NormalOrder[a,retTail]}]];
	If[pos==aLength,
		normOrderab = NormalOrder[a,b];
		abLength=LengthOfExpression[normOrderab];
		If[abLength=!=aLength+ bLength,(*Message[MoveTerm::changedForm, a,b,normOrderab];*)
			{retExpr, retTail}={normOrderab,0},
			{retExpr, retTail}=MoveTermRight[normOrderab,pos];
		];

		Return[{NormalOrder[retExpr,c],NormalOrder[retTail ,c]-MoveAss[a,b,c]}]
	];

	{retExpr, retTail}=MoveTermRight[a ,pos];

	{NormalOrder[retExpr,NormalOrder[b,c]],NormalOrder[retTail,NormalOrder[b,c]]}
];

MoveTermRight[0,pos_Integer] := {0,0};

MoveTermRight[ NormalOrder[NormalOrder[a_,b_] ,c_], pos_Integer] := Module[{aLength,bLength,cLength,retExpr,retTail,normOrderbc,bcLength},
	(*Print["tjim"];*)
	aLength=LengthOfExpression[a];
	bLength=LengthOfExpression[b];
	cLength=LengthOfExpression[c];
	(*Print[aLength];
	Print[bLength];
	Print[cLength];
	Print[pos];
	Print[pos>(aLength+bLength)];
	Print[pos==(aLength+bLength)]; *)

	If[pos>(aLength+bLength),
		(*Print["A"];*)
		{retExpr, retTail}=MoveTermRight[c , pos-aLength-bLength];
		Return[{NormalOrder[NormalOrder[a,b], retExpr],NormalOrder[NormalOrder[a,b],retTail]}]
	];
	If[pos==(aLength+bLength),
		
		(*Print["B"];
		Print["b"];
		Print[b];
		Print["c"];
		Print[c];
		Print["pos"];
		Print[pos];
*)
		normOrderbc = NormalOrder[b,c];
		bcLength=LengthOfExpression[normOrderbc];
		If[bcLength=!=bLength+ cLength,
			(*Message[MoveTerm::changedForm, b,c,normOrderbc];*) {retExpr, retTail}={normOrderbc,0},
			{retExpr, retTail}=MoveTermRight[normOrderbc,pos-aLength];
		];
		(*Print[{retExpr, retTail}];*)
		Return[{NormalOrder[a,retExpr],NormalOrder[a,retTail] + MoveAss[a,b,c]}]
	];

	(*Print["C"];*)

	{retExpr, retTail}=MoveTermRight[NormalOrder[a,b] ,pos];
	(*Print[{retExpr, retTail}];*)

	{NormalOrder[retExpr,c],NormalOrder[retTail,c]}
];


MoveTerm[a_?NumericQ * b_,pos_Integer,move_Integer]:=a*MoveTerm[b,pos,move];

MoveTerm[expr_,{pos_Integer, restpos___},{move_Integer,restmove___}]:=Module[{newFlatList,internExpr,tail,flatlist,replRules,retExpr,rettail},
replRules = {Lambda`Private`MoveAss->NormalOrderAssociator , Lambda`Private`MoveCom-> NormalOrderCommutator};

internExpr = expr;
flatlist = expr/. NormalOrder->List//Flatten;
tail =0;
For[i=0,i<move,i++,
(*
Print["i"];Print[i];
Print["internExpr"];Print[internExpr//FullForm];
Print["tail"];Print[tail];
Print["pos+i"];Print[pos+i];
*)
	{internExpr,tail} = MoveTermRight[internExpr,pos+i]+{0,tail};
	(*Expression may have changed when one element is moved. Check for this, and if this is the case, return the new expression. *)
	newFlatList = ({internExpr}/. NormalOrder->List//Flatten)/. _?NumericQ * a_ -> a;
	(*
Print["flatlist"];Print[flatlist];
	Print["newFlatList"];Print[newFlatList];
	Print["Complement[flatlist,newFlatList]"];Print[Complement[flatlist,newFlatList]];
*)
	If[Complement[flatlist,newFlatList]=!= {},Return[internExpr+tail/.replRules]];
];

{retExpr,rettail}=MoveTerm[internExpr,{restpos},{restmove}];

(retExpr+rettail+tail)/.replRules
];

MoveTerm[expr_,pos_Integer,move_Integer]:=MoveTerm[expr,{pos},{move}];
MoveTerm[expr_,{},{}]:={expr,0};



SortDerivativesFirst = True;


(*Sort on first number of indices down, then up, then derivatives*)
FieldsOrderedQ[Field[sym_Symbol,downInd1_List,upInd1_List,derivatives1_List],Field[sym_Symbol,downInd2_List,upInd2_List,derivatives2_List] ,OrderOfFields_List]:=Module[{},
	If[(Length[downInd1]===Length[downInd2]),
	If[(Length[upInd1]===Length[upInd2]),
	If[(Length[derivatives1]===Length[derivatives2]),
		If[downInd1 !={},Return[OrderedQ[{downInd1,downInd2}]  ] ];
		If[upInd1 !={},Return[OrderedQ[{upInd1,upInd2}]  ] ];
	,(Length[derivatives1]<=Length[derivatives2])]
	,(Length[upInd1]<=Length[upInd2])]
	,(Length[downInd1]<=Length[downInd2])]
]; 
FieldsOrderedQ[Field[sym1_Symbol,___],Field[sym2_Symbol,___] ,OrderOfFields_List]:=Module[{},
MatchQ[OrderOfFields,{___,sym1,___,sym2,___}] || ! MemberQ[OrderOfFields,sym1]
]/; MemberQ[OrderOfFields,sym2]  ;
FieldsOrderedQ[Field[sym1_Symbol,___],Field[sym2_Symbol,___] ,_List]:=Module[{},
OrderedQ[{sym1,sym2}]
];
FieldsOrderedQ[Field[sym_Symbol,___],TD[Field[sym_Symbol,___] ],_List]:=!SortDerivativesFirst;
FieldsOrderedQ[TD[Field[sym_Symbol,___]],Field[sym_Symbol,___] ,_List]:=SortDerivativesFirst;

FieldsOrderedQ[TD[f1_],TD[f2_],or_List] := FieldsOrderedQ[f1,f2 ,or];
FieldsOrderedQ[f1_,TD[f2_],or_List] := FieldsOrderedQ[f1,f2 ,or];
FieldsOrderedQ[TD[f1_],f2_,or_List] := FieldsOrderedQ[f1,f2 ,or];



FieldsOrderedQ[Field[sym_Symbol,___],SD[Field[sym_Symbol,___] ],_List]:=!SortDerivativesFirst;
FieldsOrderedQ[SD[Field[sym_Symbol,___]],Field[sym_Symbol,___] ,_List]:=SortDerivativesFirst;

FieldsOrderedQ[SD[f1_],SD[f2_],or_List] := FieldsOrderedQ[f1,f2 ,or];
FieldsOrderedQ[f1_,SD[f2_],or_List] := FieldsOrderedQ[f1,f2 ,or];
FieldsOrderedQ[SD[f1_],f2_,or_List] := FieldsOrderedQ[f1,f2 ,or];



SortExpression[a_Plus, OrderOfFields_List]:=Map[SortExpression[#,OrderOfFields ]&,a]; 
SortExpression[TD[expr_], OrderOfFields_List]:=TD[SortExpression[expr, OrderOfFields]];
SortExpression[SD[expr_], OrderOfFields_List]:=SD[SortExpression[expr, OrderOfFields]];
SortExpression[a_?NumericQ, _List]:=a;
SortExpression[a_?OddNumericQ, _List]:=a; 
SortExpression[Times[a_?NumericQ,b_],OrderOfFields_List] := Times[a,SortExpression[b, OrderOfFields]];
SortExpression[Times[a_?OddNumericQ,b_],OrderOfFields_List] := Times[a,SortExpression[b, OrderOfFields]];
SortExpression[expr_, OrderOfFields_List]:=Module[{newFlatList,expressionToSort=expr, replRules, nrOfElementsSorted=0,flatlist,sortedFlatlist, elem1,elem2,tailExpr=0,j=0,i},
	replRules = {Lambda`Private`MoveAss->NormalOrderAssociator , Lambda`Private`MoveCom-> NormalOrderCommutator};
	flatlist = expressionToSort/. NormalOrder->List//Flatten;
	sortedFlatlist = Sort[flatlist,FieldsOrderedQ[#1,#2,OrderOfFields]&];

(*
Print["expressionToSort"];Print[expressionToSort];
Print["flatlist"];Print[flatlist];
Print["sortedFlatlist"];Print[sortedFlatlist];
Print[MapIndexed[ (#1===Extract[sortedFlatlist,#2])&,flatlist]];
Print["nrOfElementsSorted"];Print[ LengthWhile[MapIndexed[ (#1===Extract[sortedFlatlist,#2])&,flatlist],TrueQ]];
*)
	While[  nrOfElementsSorted = LengthWhile[MapIndexed[ (#1===Extract[sortedFlatlist,#2])&,flatlist],TrueQ];nrOfElementsSorted< Length[flatlist] && j++ <  $RecursionLimit,  
		For[i=nrOfElementsSorted+1,i<Length[flatlist],i++,
			elem1 = flatlist[[i]];
			elem2 = flatlist[[i+1]];
			If[!FieldsOrderedQ[elem1,elem2,OrderOfFields],
				(*Print["expressionToSort loop"];Print[expressionToSort];
Print["i loop"];Print[i];*)
				flatlist=ReplacePart[flatlist,{i->flatlist[[i+1]],(i+1)->flatlist[[i]]}];
				{expressionToSort,tailExpr} = MoveTermRight[expressionToSort,i]+{0,tailExpr};
(*Expression may have changed when one element is moved. Check for this, and if this is the case, sort the new expression instead. *)

newFlatList = ({expressionToSort}/. NormalOrder->List//Flatten)/. _?NumericQ * a_ -> a;

(*
Print["expressionToSort"];Print[expressionToSort];
Print["tailExpr"];Print[tailExpr];
Print["newFlatList"];Print[newFlatList];
Print["Complement[flatlist,newFlatList]"];Print[Complement[flatlist,newFlatList]];
*)

				If[Complement[flatlist,newFlatList]=!= {},Return[SortExpression[expressionToSort,OrderOfFields] +tailExpr/.replRules ] ]



(* Print[{expressionToSort,tailExpr}]; *)
			]
		]
	];
	expressionToSort+tailExpr/.replRules
];




(*Possibility to expand superfields in components*)
DefineComponents[superfield_Symbol,constPart_Symbol,thetaPart_Symbol]:=Module[{},
SuperfieldComponentConst[superfield]=constPart;
SuperfieldComponentTheta[superfield]=thetaPart;
Grading[Field[constPart,___]]:=Grading[Field[superfield]];
Grading[Field[thetaPart,___]]:=Mod[1+Grading[Field[superfield]],2];
1];

ExpandSuperFields[f:Field[sym_Symbol ,downindices_List, upindices_List,derivatives_List]]:=Module[{},
{
{Field[SuperfieldComponentConst[sym] ,downindices, upindices,derivatives],Grading[f]},{Field[SuperfieldComponentTheta[sym] ,downindices, upindices,derivatives],Mod[Grading[f]+1,2]}
}];

ExpandSuperFields[NormalOrder[a_,b_]]:=Module[{aExpanded=ExpandSuperFields[a],bExpanded=ExpandSuperFields[b]},
{
{NormalOrder[aExpanded[[1]][[1]],bExpanded[[1]][[1]]],Mod[aExpanded[[1]][[2]]+bExpanded[[1]][[2]],2]},
{(-1)^(aExpanded[[1]][[2]])*NormalOrder[aExpanded[[1]][[1]],bExpanded[[2]][[1]]]+NormalOrder[aExpanded[[2]][[1]],bExpanded[[1]][[1]]],Mod[aExpanded[[2]][[2]]+bExpanded[[2]][[2]]+1,2]}
}];

ExpandSuperFields[a_?NumericQ*b_]:=MapAt[(a*#)&,ExpandSuperFields[b],{{1,1},{2,1}}];

ExpandSuperFields::notpropgrading = "The fields dont have proper grading. Can not add objects with different grading.";
ExpandSuperFields[Plus[a_,b__]]:=Module[{aExpanded=ExpandSuperFields[a],bExpanded=ExpandSuperFields[b]},
If[aExpanded[[1]][[2]]=!= bExpanded[[1]][[2]] || aExpanded[[2]][[2]]=!= bExpanded[[2]][[2]] ,Message[ExpandSuperFields::notpropgrading],
{{aExpanded[[1]][[1]] +bExpanded[[1]][[1]],aExpanded[[1]][[2]]},{aExpanded[[2]][[1]] +bExpanded[[2]][[1]],aExpanded[[2]][[2]]} }]];

ExpandSuperFields[TD[a_]]:=MapAt[(TD[#])&,ExpandSuperFields[a],{{1,1},{2,1}}];

ExpandSuperFields[SD[a_]]:=Module[{aExpanded=ExpandSuperFields[a]},{
{aExpanded[[2]][[1]],aExpanded[[2]][[2]]},
{TD[aExpanded[[1]][[1]]],aExpanded[[1]][[2]]}}]






(* Special field delta*)
deltaf = Field[Global`\[Delta], {a}, {b}];
Grading[Field[Global`\[Delta], ___]] := 0;

NumericQ[dim] := True;
Field[Global`\[Delta], {a_}, {a_}, ___] := dim;
TD[Field[Global`\[Delta], ___]] := 0;
SD[Field[Global`\[Delta], ___]] := 0;

NormalOrder[  Field[sym_Symbol, rest___],Field[Global`\[Delta], ind___]] := NormalOrder[Field[Global`\[Delta], ind], Field[sym, rest ]] /; sym =!= Global`\[Delta];
(*NormalOrder[ T[ Field[sym_Symbol,rest___]],Field[\[Delta],ind___]] := \
T[NormalOrder[Field[\[Delta],ind], Field[sym,rest ]]] /; sym =!= \
\[Delta];*)

(* 
NormalOrder[ Field[Global`\[Delta], ind___], TD[ f_]] := TD[NormalOrder[Field[Global`\[Delta], ind], f]];
NormalOrder[ Field[Global`\[Delta], ind___], SD[ f_]] := SD[NormalOrder[Field[Global`\[Delta], ind], f]];
*)
NormalOrder[ Field[Global`\[Delta], {deltaDown_}, {deltaUp_}, ___], Field[sym_Symbol, downInd_List, upInd_List, rest___]] := Field[sym, downInd, upInd /. deltaDown -> deltaUp, rest ] /;Length[Intersection[{deltaDown}, upInd]] =!= 0  ;
NormalOrder[ Field[Global`\[Delta], {deltaDown_}, {deltaUp_}, ___], Field[sym_Symbol, downInd_List, upInd_List, rest___]] := Field[sym, downInd /.  deltaUp -> deltaDown, upInd, rest ] /;Length[Intersection[{deltaUp}, downInd]] =!= 0  ;
NormalOrder[ Field[Global`\[Delta], {deltaDown_}, {deltaUp_}, ___], Field[sym_Symbol, downInd_List, upInd_List, derivatives_List, rest___]] := Field[sym, downInd, upInd, derivatives /.  deltaUp -> deltaDown, rest ] /; Length[Intersection[{deltaUp}, derivatives]] =!= 0  ;

LambdaBracket[ Field[Global`\[Delta], ___], _] := 0 ; 
LambdaBracket[ _, Field[Global`\[Delta], ___]] := 0 ; 


End[ ];

EndPackage[];




